import React from 'react';
import type { NextPage } from "next";
import Head from "next/head";
import Card from "../components/Card/Card";
import { useRouter } from "next/router";
import { Row, Col } from "antd";

export const titles: string[] = ["Series", "Movies"];

const Home: NextPage = () => {
  const router = useRouter();
  const handleClick = (url: string) => {
    router.push(url);
  };

  return (
    <div>
      <Head>
        <title>Pankod Front End Challange</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Row>
        {titles.map((title, index) => (
          <Col
            key={index}
            lg={{ span: 1, offset: 2 }}
            xs={{ span: 24, offset: 2 }}
          >
            <div onClick={() => handleClick(title.toLowerCase())}>
              <Card message={title} />
            </div>
          </Col>
        ))}
      </Row>
    </div>
  );
};

export default Home;
